matrix:
  include:
    - os: osx
      osx_image: xcode8.1
      language: objective-c
    - os: linux
      language: generic
      sudo: required
      dist: trusty
      env:
        - 'SWIFT_VERSIONS=(3.0.2 3.1)'
env:
  global:
    - LC_CTYPE=en_US.UTF-8
    - LANG=en_US.UTF-8
    - FRAMEWORK_NAME="RandomKit"
install: ./ci/install.sh
script: ./ci/travis.sh
